### ISSUE TITLE
数据集貌似是英文的，请问有中文数据集吗？

### ISSUE THREAD

**Issue by xyfZzz** [njucckevin/SeeClick#1]

**Comment by njucckevin** [comment]
目前SeeClick预训练和评测都主要关注英文数据（Common Crawl多数是英文网站，且下游任务也均是英文的）。虽然SeeClick的基线Qwen-VL支持中文，但不确定SeeClick在中文上的效果。

**Comment by xyfZzz** [comment]
> 目前SeeClick预训练和评测都主要关注英文数据（Common Crawl多数是英文网站，且下游任务也均是英文的）。虽然SeeClick的基线Qwen-VL支持中文，但不确定SeeClick在中文上的效果。

有计划出中文数据集吗？

**Comment by njucckevin** [comment]
暂时没有这样的计划：）

**Comment by xyfZzz** [comment]
> 暂时没有这样的计划：）

好的，谢谢
