### ISSUE TITLE
Broken link to ScreenSpot

### ISSUE THREAD

**Issue by Yingrjimsch** [njucckevin/SeeClick#10]
I wanted to check out the annotated images for ScreenSpot. Unfortunately the link in the readme.md is broken [ScreenSpot](https://box.nju.edu.cn/d/5b8892c1901c4dbeb715/). Can you provide the benchmark in another way?

Thank you 😄

**Comment by njucckevin** [comment]
Hi, the [ScreenSpot](https://box.nju.edu.cn/d/5b8892c1901c4dbeb715/) link is ok for my chrome browser. And I will upload a backup link with Google Drive or Baiduyun soon.

**Comment by Yingrjimsch** [comment]
Hi, looks like it was a network problem or something 2hrs ago I got an error that the page could not be found and now it works again. Thanks for your fast reply and for the interesting work 😄
