### ISSUE TITLE
many images not found when I process AITW dataset 

### ISSUE THREAD

**Issue by Yuan-Lin615** [njucckevin/SeeClick#15]
I download AITW [anno](https://box.nju.edu.cn/f/1245c74fc09b4565a235/) and process AITW dataset like this.
```
cd agent_tasks
python aitw_process.py --imgs_dir aitw_imgs
```
Is this normal.
<img width="1686" alt="image" src="https://github.com/njucckevin/SeeClick/assets/133587787/e46f68b7-b023-45e4-a301-bb4ab6e65fd7">

**Comment by njucckevin** [comment]
Hi

Have you downloaded the AITW [screenshots](https://box.nju.edu.cn/f/96ba5115bae24eaaa44e/) mentioned in the Preparation section of `readme_agent.md`? The `aitw_imgs` should be the actual dir of the downloaded images.

**Comment by linxid** [comment]
Thanks for the reply, I reextracted the file and no more problems. When I was working with the `widget_captioning.json` data, I noticed that many of the images don't exist, is this normal.  There are only 56044 images in `rico_images`

**Comment by linxid** [comment]
<img width="1679" alt="image" src="https://github.com/njucckevin/SeeClick/assets/16094085/d8f0f29c-7ad2-42ff-aa9e-e1d60e7db742">

**Comment by njucckevin** [comment]
How many images are in the `combined` dir in your case? For me, all the images in `widget_captioning.json` can be found in `combined` directory.

**Comment by linxid** [comment]
56044 images. I download dataset in this [url](https://box.nju.edu.cn/f/7ae5e9bd4bf840d4add3/)

**Comment by njucckevin** [comment]
Do you have enough local storage space on your computer? I found that if there's not enough storage space it will cause the unzip to be missing some files.

**Comment by LeeOrange-is-me** [comment]
maybe when you unzip the AITW pictures file  , you get the dir called "aitw_images" rather than "aitw_imgs"... ...
