### ISSUE TITLE
Questions about specific APPs in ScreenSpot benchmark.

### ISSUE THREAD

**Issue by XinrunXu** [njucckevin/SeeClick#16]
Which mobile apps, desktop apps, and web pages were used in your ScreenSpot benchmark? Can you list it in detail?

**Comment by njucckevin** [comment]
Hi,

For web pages, we use several websites provided in WebArena, i.e., Development (GitLab), Shopping (OneStopShop and CMS), Forum (Reddit) and Tools (OpenStreetMap and Wikipedia). For mobile and desktop, we ask the annotators to collect screenshots, so there are no restrictions regarding apps; It looks like a lot of the screenshots are official apps, such as Apple's Setting app.

**Comment by XinrunXu** [comment]
Thank You!
