### ISSUE TITLE
seeclick-aitw checkpoint publish?

### ISSUE THREAD

**Issue by zzh-www** [njucckevin/SeeClick#17]
有计划发布seeclick在aitw微调后的模型权重嘛？🙏

**Comment by njucckevin** [comment]
我正在上传AITW微调的ckpt到[Huggingface](https://huggingface.co/cckevinn/SeeClick-aitw)，应该今晚可以上传完成，你可以试一试~
I'm uploading the AITW fine-tuned LoRA checkpoint (maybe completed tonight). You can have a try~

**Comment by zzh-www** [comment]
太棒了！谢谢!
That's awesome! Thank you!
