### ISSUE TITLE
Great work! I wonder if seeclick-MiniWob checkpoint and Miniwob 2.8k data are released :)

### ISSUE THREAD

**Issue by XuRui314** [njucckevin/SeeClick#18]

**Comment by njucckevin** [comment]
Hi, 

The 2.8K MiniWob training data has been released at https://github.com/njucckevin/SeeClick/blob/main/agent_tasks/readme_agent.md. And I will upload the SeeClick-miniwob checkpoint for testing soon.

**Comment by XuRui314** [comment]
Really thx for sharing!

**Comment by njucckevin** [comment]
The [SeeClick-miniwob](https://huggingface.co/cckevinn/SeeClick-miniwob) is now released.
