### ISSUE TITLE
Any plan to release pretraining code?

### ISSUE THREAD

**Issue by ltzheng** [njucckevin/SeeClick#19]
Thank you for your great work. It seems that the pretraining code is not yet open. Do you plan to open-source it?

**Comment by njucckevin** [comment]
Hi, sorry for a bit late.
The script used for pre-training is actually the same as the script used for downstream agent task fine-tuning. 
Simply organize the data as described in  [readme_data.md](https://github.com/njucckevin/SeeClick/blob/main/readme_data.md) according the Qwen-VL format for `--data-path`, and replace `pretrain-ckpt` with the directory of pre-trained Qwen-VL model.
Do you mean the detailed data processing code we used?

**Comment by ltzheng** [comment]
Thanks for prompt response. Yes I am looking for the data processing code to generate the json file needed for training.

**Comment by njucckevin** [comment]
I will try to update this part of the code in several days.

**Comment by njucckevin** [comment]
The pre-training scripts are now released :)

**Comment by ltzheng** [comment]
Great! Thank you very much.
