### ISSUE TITLE
Model on huggingface

### ISSUE THREAD

**Issue by DanielProkhorov** [njucckevin/SeeClick#2]
Hello,

very interesting fine tune! 

Would you please upload the model to huggingface?

**Comment by njucckevin** [comment]
Hi, the model has been uploaded to huggingface (https://huggingface.co/cckevinn/SeeClick). Check the new readme for inference~

**Comment by DanielProkhorov** [comment]
> Hi, the model has been uploaded to huggingface (https://huggingface.co/cckevinn/SeeClick). Check the new readme for inference~

Thanks mate! 

I've tried your model, the model path seems to be outdated within the readme"**cckevinn/SeeClick**"

**Comment by njucckevin** [comment]
`SeeClick-ckpt-dir` is a placeholder for the path to the checkpoint, currently it doesn't seem to load directly through `cckevinn/SeeClick`, I'm working on fixing it. Thanks~
