### ISSUE TITLE
No LICENSE specified in repo

### ISSUE THREAD

**Issue by tellarin** [njucckevin/SeeClick#21]
I've noticed that unfortunately there is no license specified for either the code or the dataset represented in this repository. 

Could you please add a LICENSE file in the repo to clarify under what conditions the code and data are released? Otherwise it is not possible for many people to try, reproduce, or help build on your work.

I'd like to suggest a permissive open source license, in case you don't already have a specific one in mind. 

Thanks for your attention. Hope this issue can be sorted out soon.

**Comment by njucckevin** [comment]
Added an Apache 2.0 license.

**Comment by tellarin** [comment]
@njucckevin Thank you very much for the clarification. I'll close this issue now.
