### ISSUE TITLE
How is Qwen finetuned for evaluating?

### ISSUE THREAD

**Issue by XuRui314** [njucckevin/SeeClick#22]
Qwen and Seeclick both finetune the VIT and LLM, or does Qwen only finetune the LLM?

**Comment by njucckevin** [comment]
SeeClick uses LoRA to fine-tune customized parameters in both ViT and LLM, as in finetune/finetune.py lines 315-327.

**Comment by XuRui314** [comment]
I'm sorry for not being able to express myself clearly. Qwen and SeeClick are both finetuned in downstream dataset like: Table 4, i wonder how the original Qwen model is finetuned in this case.

**Comment by njucckevin** [comment]
Both Qwen-VL and SeeClick fine-tune the ViT and LLM using LoRA. 
In our downstream task experiments (Table 2/3/4), the only difference between SeeClick and Qwen-VL is the loaded checkpoint (i.e., the SeeClick-pretrain and original Qwen-VL), the rest of the fine-tuning settings are identical.

**Comment by XuRui314** [comment]
Thank you
