### ISSUE TITLE
The gpu cost when running finetune/finetune_lora_ds.sh

### ISSUE THREAD

**Issue by zhengshuo1** [njucckevin/SeeClick#24]
Hello, may I ask about the gpu cost when running finetune_lora_ds.sh. I have a 49GB*4 machine, however, when I ran the shell, it appeared to be out of memory.

**Comment by njucckevin** [comment]
Hi,

Our fine-tuning takes about 24h on 8\*A100(80G). I suppose 49G*4 GPU should be ok, referring to Qwen-VL's fine-tuning [guide](https://github.com/QwenLM/Qwen-VL?tab=readme-ov-file#profiling-of-memory-and-speed). You may need to reduce the `micro-batch-size`.

**Comment by zhengshuo1** [comment]
> Hi,
> 
> Our fine-tuning takes about 24h on 8*A100(80G). I suppose 49G*4 GPU should be ok, referring to Qwen-VL's fine-tuning [guide](https://github.com/QwenLM/Qwen-VL?tab=readme-ov-file#profiling-of-memory-and-speed). You may need to reduce the `micro-batch-size`.

thanks, when I reduce micro-batch-size to 1, it is ok. I have another question. If I use the parameter max-length,  it is shown "Unknown parameter passed".

**Comment by njucckevin** [comment]
The parameters are defined in `finetune/finetune_lora_ds.sh`, which include `--max-length`. What is your fine-tuning command?

**Comment by zhengshuo1** [comment]
> The parameters are defined in `finetune/finetune_lora_ds.sh`, which include `--max-length`. What is your fine-tuning command?

sorry. I tried it again, and there was nothing wrong.
