### ISSUE TITLE
Question about Vision-Language Adapter

### ISSUE THREAD

**Issue by ChenYang1024** [njucckevin/SeeClick#30]
Hello, thanks for sharing your interesting research!

May I ask about the  the structure of the Vision-Language Adapter mentioned in this paper and how it works during fine-tuning.
Is this adapter introduced to address a semantic gap between the embeddings of images obtained through ViT and instructions, which leads to poor performance when directly concatenated?

**Comment by njucckevin** [comment]
Hi,

Do you mean the Vision-Language Adapter shown in Figure 2 (a)? Sorry for the possible misunderstanding, Figure 2 (a) is just a schematic. This adapter is introduced by our baseline model Qwen-VL itself for connecting ViT and LLM, SeeClick did not modify the model structure of Qwen-VL.
Introducing an adapter to connect ViT and LLM is a common practice in current Large Vision-Language Models, e.g. the MLP layers in LLaVA and the Q-former in our case. These adapters are considered to contribute to vision language alignment.

**Comment by ChenYang1024** [comment]
I got it! 
Thanks for your prompt response.
