### ISSUE TITLE
作者您好！关于finetune后模型测试时读取模型报错

### ISSUE THREAD

**Issue by dmndxld** [njucckevin/SeeClick#31]
您好！我用finetune下的finetune_lora_ds.sh脚本微调了我自己的aitw数据集，模型是原seeclick的base模型，然后用agent_tasks下的aitw_test.py测试时，在模型读取时发生了如下报错
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:04<00:00,  2.38it/s]
Traceback (most recent call last):
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/u2020010349/.vscode-server/extensions/ms-python.debugpy-2024.6.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/u2020010349/share/yc/FL_agent/SeeClick-main/agent_tasks/lh_make/test_my.py", line 74, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(model_path, device_map="cuda", trust_remote_code=True).eval()  # load with lora checkpoint
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/site-packages/peft/auto.py", line 123, in from_pretrained
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 847, in from_pretrained
    return tokenizer_class.from_pretrained(
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/u2020010349/.cache/huggingface/modules/transformers_modules/checkpoint-1589/tokenization_qwen.py", line 120, in __init__
    super().__init__(**kwargs)
  File "/home/u2020010349/.conda/envs/FLAGENT/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/home/u2020010349/.cache/huggingface/modules/transformers_modules/checkpoint-1589/tokenization_qwen.py", line 229, in _add_tokens
    if surface_form not in SPECIAL_TOKENS + self.IMAGE_ST:
AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'
我有去qwen下查询相关issue，发现了一个[类似的问题](https://github.com/QwenLM/Qwen-VL/issues/287)，他这里说的是tokenization_qwen.py在136行加入super().__init__(**kwargs)，奇怪的是我的文件中这行代码位于120行（整个QWenTokenizer类的init的第一句），我也照猫画虎的把这行放到了IMAGE_ST的下面，结果会发生新的报错
Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.transformer.wte.modules_to_save.default.weight: copying a param with shape torch.Size([151936, 4096]) from checkpoint, the shape in current model is torch.Size([151860, 4096]).
	size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([151936, 4096]) from checkpoint, the shape in current model is torch.Size([151860, 4096]).
  File "/home/u2020010349/share/yc/FL_agent/SeeClick-main/agent_tasks/lh_make/test_my.py", line 74, in <module>
    model = AutoPeftModelForCausalLM.from_pretrained(model_path, device_map="cuda", trust_remote_code=True).eval()  # load with lora checkpoint
RuntimeError: Error(s) in loading state_dict for PeftModelForCausalLM:
	size mismatch for base_model.model.transformer.wte.modules_to_save.default.weight: copying a param with shape torch.Size([151936, 4096]) from checkpoint, the shape in current model is torch.Size([151860, 4096]).
	size mismatch for base_model.model.lm_head.modules_to_save.default.weight: copying a param with shape torch.Size([151936, 4096]) from checkpoint, the shape in current model is torch.Size([151860, 4096]).
您在当时有遇到类似的情况吗？有什么思路可以帮助我解决吗？感谢！

**Comment by dmndxld** [comment]
```python
model = AutoPeftModelForCausalLM.from_pretrained(model_path, device_map="cuda", trust_remote_code=True).eval()  # load with lora checkpoint
```
这一句读取时报错的

**Comment by njucckevin** [comment]
我当时没有遇到这个问题。
我看了一下，我上传的ckpt中的tokenization_qwen.py和目前Qwen-VL官方huggingface上的tokenization_qwen.py是有一些不一样的地方的，例如下面的区别。但这个不是我改动的，应该是Qwen-VL在我下载ckpt之后更新过代码，你可以检查一下哪里不同debug看看。
<img width="1724" alt="截屏2024-05-11 19 00 45" src="https://github.com/njucckevin/SeeClick/assets/52454979/4555f711-2104-4681-a09b-ad83c6d26e68">

**Comment by dmndxld** [comment]
> 我当时没有遇到这个问题。 我看了一下，我上传的ckpt中的tokenization_qwen.py和目前Qwen-VL官方huggingface上的tokenization_qwen.py是有一些不一样的地方的，例如下面的区别。但这个不是我改动的，应该是Qwen-VL在我下载ckpt之后更新过代码，你可以检查一下哪里不同debug看看。 <img alt="截屏2024-05-11 19 00 45" width="1724" src="https://private-user-images.githubusercontent.com/52454979/329776201-4555f711-2104-4681-a09b-ad83c6d26e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTQ3MTIsIm5iZiI6MTcxNTQ5NDQxMiwicGF0aCI6Ii81MjQ1NDk3OS8zMjk3NzYyMDEtNDU1NWY3MTEtMjEwNC00NjgxLWEwOWItYWQ4M2M2ZDI2ZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA2MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MTBlZDEyYzQ3NTBlZjRiZDM1NjczM2YwNDRkNWI5MjdkZWFjMWRkYzcxMTE0NGRmMzRlN2I0ODUzMmIxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rOKrvgRL4dautqZ2whUxnsTco6o3daWsI4QS0NnxgII">

感谢您的及时回复！我推测这个问题可能是qwen的模型有改动？我用qwen去做finetune之后，再[这个方法](https://github.com/QwenLM/Qwen-VL/issues/287)修改后就可以了。但是seeclick的base模型finetune之后好像会mismatch模型size

**Comment by carachu1** [comment]
> > 我当时没有遇到这个问题。 我看了一下，我上传的ckpt中的tokenization_qwen.py和目前Qwen-VL官方huggingface上的tokenization_qwen.py是有一些不一样的地方的，例如下面的区别。但这个不是我改动的，应该是Qwen-VL在我下载ckpt之后更新过代码，你可以检查一下哪里不同debug看看。 <img alt="截屏2024-05-11 19 00 45" width="1724" src="https://private-user-images.githubusercontent.com/52454979/329776201-4555f711-2104-4681-a09b-ad83c6d26e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTQ3MTIsIm5iZiI6MTcxNTQ5NDQxMiwicGF0aCI6Ii81MjQ1NDk3OS8zMjk3NzYyMDEtNDU1NWY3MTEtMjEwNC00NjgxLWEwOWItYWQ4M2M2ZDI2ZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA2MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MTBlZDEyYzQ3NTBlZjRiZDM1NjczM2YwNDRkNWI5MjdkZWFjMWRkYzcxMTE0NGRmMzRlN2I0ODUzMmIxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rOKrvgRL4dautqZ2whUxnsTco6o3daWsI4QS0NnxgII">
> 
> 感谢您的及时回复！我推测这个问题可能是qwen的模型有改动？我用qwen去做finetune之后，再[这个方法](https://github.com/QwenLM/Qwen-VL/issues/287)修改后就可以了。但是seeclick的base模型finetune之后好像会mismatch模型size

这个tokenization_qwen.py文件是Qwen-VL-Chat里的嘛？我试了您提到的方法，运行model = AutoPeftModelForCausalLM.from_pretrained(model_path, device_map="cuda", trust_remote_code=True).eval()这一行还是出现AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'这个问题？

**Comment by dmndxld** [comment]
> > > 我当时没有遇到这个问题。 我看了一下，我上传的ckpt中的tokenization_qwen.py和目前Qwen-VL官方huggingface上的tokenization_qwen.py是有一些不一样的地方的，例如下面的区别。但这个不是我改动的，应该是Qwen-VL在我下载ckpt之后更新过代码，你可以检查一下哪里不同debug看看。 <img alt="截屏2024-05-11 19 00 45" width="1724" src="https://private-user-images.githubusercontent.com/52454979/329776201-4555f711-2104-4681-a09b-ad83c6d26e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0OTQ3MTIsIm5iZiI6MTcxNTQ5NDQxMiwicGF0aCI6Ii81MjQ1NDk3OS8zMjk3NzYyMDEtNDU1NWY3MTEtMjEwNC00NjgxLWEwOWItYWQ4M2M2ZDI2ZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDA2MTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MTBlZDEyYzQ3NTBlZjRiZDM1NjczM2YwNDRkNWI5MjdkZWFjMWRkYzcxMTE0NGRmMzRlN2I0ODUzMmIxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rOKrvgRL4dautqZ2whUxnsTco6o3daWsI4QS0NnxgII">
> > 
> > 
> > 感谢您的及时回复！我推测这个问题可能是qwen的模型有改动？我用qwen去做finetune之后，再[这个方法](https://github.com/QwenLM/Qwen-VL/issues/287)修改后就可以了。但是seeclick的base模型finetune之后好像会mismatch模型size
> 
> 这个tokenization_qwen.py文件是Qwen-VL-Chat里的嘛？我试了您提到的方法，运行model = AutoPeftModelForCausalLM.from_pretrained(model_path, device_map="cuda", trust_remote_code=True).eval()这一行还是出现AttributeError: 'QWenTokenizer' object has no attribute 'IMAGE_ST'这个问题？

不是。这个文件准确来说应该是运行finetune后自动存储在你finetune的checkpoint的文件夹下，去修改这里的试试看。

**Comment by zlsjsj** [comment]
> 我当时没有遇到这个问题。 我看了一下，我上传的ckpt中的tokenization_qwen.py和目前Qwen-VL官方huggingface上的tokenization_qwen.py是有一些不一样的地方的，例如下面的区别。但这个不是我改动的，应该是Qwen-VL在我下载ckpt之后更新过代码，你可以检查一下哪里不同debug看看。 <img alt="截屏2024-05-11 19 00 45" width="1724" src="https://private-user-images.githubusercontent.com/52454979/329776201-4555f711-2104-4681-a09b-ad83c6d26e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDI1MDEsIm5iZiI6MTcxODcwMjIwMSwicGF0aCI6Ii81MjQ1NDk3OS8zMjk3NzYyMDEtNDU1NWY3MTEtMjEwNC00NjgxLWEwOWItYWQ4M2M2ZDI2ZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA5MTY0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZjI4MzQzOGUyZjFkODllMTJhMWIxOWQ5ODMyNWNlZThlNGIwNjUxYWZjMTdiYTlhOTVlNWQxNDliMWEwOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W4PUDtawFdDvRrycXYCOtvJul0qxKlPLQN49Aj8RXjM">

你好，我现在也遇到了这个问题，请问你那边下载的qw是哪个版本或者commit id呢

**Comment by njucckevin** [comment]
<img width="1593" alt="截屏2024-06-19 16 57 12" src="https://github.com/njucckevin/SeeClick/assets/52454979/53109aae-6424-4e6c-a3d0-026181431dac">
或许是Qwen-VL的这次commit导致的？我应该是在23年的12月份在hf上下载的Qwen-VL。你也可以尝试下上面提到的方法~
