### ISSUE TITLE
作者您好，在微调使用seeclick ckpt时loss为0

### ISSUE THREAD

**Issue by cbigeyes** [njucckevin/SeeClick#33]
作者您好，
我在使用finetune/finetune_lora_ds.sh做微调，并使用huggingface上的seeclick模型作为base加载后，loss从一开始就为0，请问有遇到过这样的情况吗。
PS：使用QWEN VL Chat int4作为base时，没有上述问题

**Comment by njucckevin** [comment]
您好，我在微调时没有遇到这样的情况。loss一开始就为0肯定是不正常的，可以看看是哪步出了问题？
另外我没有尝试过int4版本的微调，你有试过标准的Qwen-VL checkpoint可以正常微调吗？

**Comment by boyugou** [comment]
你好，我也遇到了相同的情况，请问有什么后续发现吗？基本上第一步之后就从4跳到了0 @cbigeyes

**Comment by boyugou** [comment]
should add:

`--bf16 True \`

to the script. @njucckevin

**Comment by boyugou** [comment]
> 你好，我也遇到了相同的情况，请问有什么后续发现吗？基本上第一步之后就从4跳到了0 @cbigeyes

follow up:

1. should make sure keeping bf16 in the scripts (and make sure your hardwares support it. For example, >=A100):

`--bf16 True \`

2.
providing both:

--model_name_or_path Qwen/Qwen-VL-Chat\
    --qwen_path Qwen/Qwen-VL-Chat \
