### ISSUE TITLE
PC screens in ScreenSpot data are cropped

### ISSUE THREAD

**Issue by UeFan** [njucckevin/SeeClick#34]
Dear authors, I am very interested in the ScreenSpot benchmark you created. I wish to ask if you have the original screens for PCs and would like to share them. The reason is that I found those in the ScreenSpot benchmark are mostly cropped. The cropped screens lost a lot of information.

Thanks a lot.

**Comment by njucckevin** [comment]
Thank you for your interest in our work.

But unfortunately I don't have the original PC screen. Many of the screenshots were taken by the annotator using the screenshot tool to directly capture a portion of the screen, such as an application window or a corner region.
