### ISSUE TITLE
The JSON for the 10k web samples?

### ISSUE THREAD

**Issue by Mihaiii** [njucckevin/SeeClick#42]
Hello!

I'm trying to do a run on Qwen 2 VL 7B and I have a dataset map issue for the entire dataset (1010402 samples) when trying to finetune with [LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory).
 
 
So I decided to try to finetune with a subset containing only 10k web images, but I don't have the JSON link. Could you please share that too?

> for convenience we also provide a [subset](https://box.nju.edu.cn/f/813897fc4edc440a9e12/) of 10,000 images.

The link from the next sentence is of the JSON of the entire web dataset samples.
source: https://github.com/njucckevin/SeeClick/blob/main/readme_data.md#web-data

**Comment by njucckevin** [comment]
Hi,

The 10k dataset is a subset of the 270k screenshots. So you can use the original annotation `The annotation elements and text are available at [here](https://box.nju.edu.cn/f/3b0f6ccb8bed476c8e39/)` and filter the images in the 10k subset?

**Comment by Mihaiii** [comment]
Alright, thank you, in the meantime I realised that I can't really use LlaMA-Factory because it seems to require to have the entire tokenized dataset loaded into RAM.

In any case, I'm closing this one.
