### ISSUE TITLE
prompt used for gpt models for evaluation

### ISSUE THREAD

**Issue by Vsanh** [njucckevin/SeeClick#44]
Hi,
can you point me to the prompt you used to evaluate the gpt models on screenspot?
is it this one?
https://github.com/njucckevin/SeeClick/blob/b30506bf1f07458c64468f3a9aa442bf4612bc16/pretrain/screenspot_test.py#L52

**Comment by njucckevin** [comment]
Hi, 
the prompt for GPT model is in https://github.com/njucckevin/SeeClick/issues/39.

**Comment by Vsanh** [comment]
perfect thank you!
