### ISSUE TITLE
Could you please provide a list of the Apps used in curating ScreenSpot benchmark?

### ISSUE THREAD

**Issue by ZJULiHongxin** [njucckevin/SeeClick#47]
Thank you for open-sourcing this great work!

I also plan to collect my own test samples in the same scenarios as ScreenSpot. Could the authors offer a list of the names of the Apps used in the ScreenSpot benchmark?

I would appreciate it if you could help me. Thank you very much in advance. @njucckevin @QiushiSun @chuyg1005

**Comment by njucckevin** [comment]
Hi, 

Thank you for your interest in our work. During the construction of the dataset, we asked the annotator to label common apps and operations, but unfortunately, we didn't record the names of the apps. 
So I think if needed, you may need to manually count these other apps, except for the web category which contains only 4 websites in  WebArena.

**Comment by ZJULiHongxin** [comment]
Thank you for the quick reply! @njucckevin
