### ISSUE TITLE
请问AITW separate的设置是什么样的

### ISSUE THREAD

**Issue by XuRui314** [njucckevin/SeeClick#48]
好像aitw目前给的脚本只是unified的sft，如果是separate的话具体的训练设置是否一致，我按照unified设置（3e-5和10epoch，只取10epoch训完的模型评测）在各个子集上sft后评测了一下，和论文汇报的结果有较大出入，请问能给出一些建议吗，谢谢

**Comment by njucckevin** [comment]
separate训练是指什么？

**Comment by XuRui314** [comment]
您好，指的是论文中Table 5: Separate v.s. unified training performance.

**Comment by njucckevin** [comment]
这个separate并不是指在AITW的5个domain上分别训练一个模型，而是指在三个任务MiniWob和AITW和Mind2Web上分别训练模型；例如里面的Table5里的59.3就是Table3汇报的AITW的结果

**Comment by XuRui314** [comment]
好的谢谢，还有个问题就是我在复现Qwen-VL在aitw unified微调的结果时，也遇到了性能不足的问题：
https://github.com/njucckevin/SeeClick/issues/43#issuecomment-2358257912
参数设置应该和仓库中保持一致，请问测试的模型是取最后训完10个epoch的那个还是根据validation set去选择用哪个checkpoint

**Comment by njucckevin** [comment]
用validation set，但在10个epoch附近我印象中应该是在test set上性能也差不多的
