### ISSUE TITLE
请问AITW的点击坐标是XY还是YX？

### ISSUE THREAD

**Issue by ZJULiHongxin** [njucckevin/SeeClick#49]
@njucckevin  作者您好！我这边跑了aitw_test.py，已经复现出seeclick paper里的点数，但是对测评过程有点疑问?

1. aitw_data_test.json里annot_position是[y,x,h,w]吗？
2. aitw_data_test.json里 "touch": [0.621, 0.497], "lift": [0.609, 0.477] 格式是 [x,y] 还是 [y,x]？

**Comment by njucckevin** [comment]
aitw的标注和官方的评测函数中，都是以[y,x,h,w]为标注的（所以annot_position应该是[y,x,h,w]；但seeclick的训练过程是以[x, y]为输出的；当时注意到了这个，所以在评测的时候不管是ref还是模型的预测都是在计算指标前调转了[x, y]变为[y, x]，以确保和官方评测一致：
https://github.com/njucckevin/SeeClick/blob/b30506bf1f07458c64468f3a9aa442bf4612bc16/agent_tasks/action_matching.py#L272
我印象里是这样，当时注意到了这个xy顺序不统一的问题；你可以检查下现在的代码逻辑是不是符合预期

**Comment by ZJULiHongxin** [comment]
多谢回复，已经弄清楚了
