### ISSUE TITLE
How to handle sliders and swipes?

### ISSUE THREAD

**Issue by DanielProkhorov** [njucckevin/SeeClick#5]
So, from the provided paper only various click actions accross different domains have been shown?

What about sliders and swipes? These do need a from (x, y) and to (x, y) coordinates. How to obtain them?

**Comment by njucckevin** [comment]
SeeClick is currently an exploratory effort, and the base model does not account for complex dragging or scrolling up and down. Further fine-tuning is needed to obtain such capabilities, such as in AITW the model needs to swipe up and down in mobile phones.
