### ISSUE TITLE
What are bounding box format in ScreenSpot Benchmark?

### ISSUE THREAD

**Issue by Endlinc** [njucckevin/SeeClick#50]
As the repo or paper mentioned, the bounding box format should be like [x1, y1, x2, y2] (top-left, bottom-right). In contrast, I observed some elements with b-box values like [879, 75, 599, 269].

Could you clarify the b-box format used in the benchmark? Many thanks.

**Comment by njucckevin** [comment]
Hi,

The bounding box format for ScreenSpot annotation is [left, top, width, height], as we then calculate the [left, top, right, bottom] in `screenspot_test.py`:
https://github.com/njucckevin/SeeClick/blob/b30506bf1f07458c64468f3a9aa442bf4612bc16/pretrain/screenspot_test.py#L69

You can also draw the bounding box in screenshots to verify the correctness.

**Comment by Endlinc** [comment]
Thank you and my problem has solved.
