### ISSUE TITLE
About the ckpt in huggingface

### ISSUE THREAD

**Issue by xyjigsaw** [njucckevin/SeeClick#51]
Nice work! I have some questions about the [ckpt](https://huggingface.co/cckevinn/SeeClick/) in huggingface.
Was it trained with LoRA? When I try to pretrain Qwen-VL using the script you provided, I can only get the adapter parameters in the output folder.

**Comment by njucckevin** [comment]
Yes, the model is trained with LoRA, similar to what we did in [downstream task training](https://github.com/njucckevin/SeeClick/blob/main/agent_tasks/readme_agent.md):
