### ISSUE TITLE
您好 有一些问题需要向您请教

### ISSUE THREAD

**Issue by positive666** [njucckevin/SeeClick#52]
1.我之前用过Claude3.5的Demo 我发现其实实现形式还是很多不一样的，最近的大模型DEMO更完整，通过内置prompt和工具调用模型自己就能实现一些操作，参考COGvlm和本仓库应该是一类还是偏向微调小模型，我打算做个简单实验，在一个场景下微调能够支持几种操作，我现在数据上有些困惑，可否具体联系方式请教交流下？
2.QWEN2VL是否支持本项目微调

**Comment by njucckevin** [comment]
本项目没有支持Qwen2-VL，Qwen2-VL和Qwen-VL有着不同的模型架构
其他问题可以邮件联系~
