### ISSUE TITLE
关于Grounding的特殊token

### ISSUE THREAD

**Issue by sugarandgugu** [njucckevin/SeeClick#53]
作者你好，很感谢你的工作，我有一个问题想咨询。
在qwen-vl的定位任务描述中，他使用到了一个<box>的特殊token，如下所示：
<img width="808" alt="image" src="https://github.com/user-attachments/assets/6d8b4c59-e82e-4a79-84c1-155a754fabbc">
请问在Seeclick的SFT数据集构建中，有利用到特殊的token嘛，还是直接输出(x,y)。在您的代码中，我没有找到相关的信息。
感谢解答！

**Comment by njucckevin** [comment]
SeeClick的SFT数据集中，不管是continual-pretrain还是downstream sft，都没有用到特殊token而是直接输出(x,y)。
实际上当时做了实验，发现用我们自定义的格式和你图里标准qwen-vl的格式，结果都是差不多的。看起来qwen-vl有比较好的格式迁移能力。

**Comment by sugarandgugu** [comment]
OK，感谢你的回复！
