### ISSUE TITLE
如何根据特定场景微调模型？

### ISSUE THREAD

**Issue by MachineDora** [njucckevin/SeeClick#54]
大佬你好！我最近在研究UI自动化（新手），想找一些模型根据特定场景下的指令来完成一些操作，例如“发一个微博”，“在bilibili上传一个视频”。然后研究了很多人的做法，在autodl上租了很多服务器来执行一些demo，包括移动端上的appAgent，以及cogAgent，或是通过GLM4V9B和Qwen2vl7b来通过特定的prompt来给出下一步的指导，但是感觉效果都不好，可能是因为我想做的场景都比较复杂，需要构建特定的知识库数据集来微调模型，或者是我的用法不对(T_T)......

根据我的理解，seeclick应该是一个基于qwenVl微调的grounding模型，可以用来标注元素的坐标，然后在agent-tasks里面分别介绍了那三个数据集微调了对应的下游任务能力，分别是web、android、simplified web的agent能力，顺序依次是先用_process构造stf data，然后finetune_lora_ds.sh，然后再_test（对吧），那么所以如果我想要基于移动端再微调，是不是应该基于hf上的seeclick-aitw模型，将原来的aitw换成我准备的数据集，再走一遍这样的流程，请问大佬我的思路对吗？

希望大佬能回答我的问题，我有什么说的不对的地方还请指出~感谢~

**Comment by njucckevin** [comment]
你好~如果你可以把你的场景整理成和AITW的格式（例如动作空间）完全一致，你可以尝试从SeeClick-AITW微调；如果格式不完全一致，最好是自定义格式然后直接用SeeClick那个basemodel微调。另外可以看一下我们最新的工作（SeeClick的升级版），[OS-Atlas](https://osatlas.github.io/)，本身具备Generalist GUI Agent的能力和未见场景的泛化性，感觉会更适合你的任务。

**Comment by MachineDora** [comment]
> 你好~如果你可以把你的场景整理成和AITW的格式（例如动作空间）完全一致，你可以尝试从SeeClick-AITW微调；如果格式不完全一致，最好是自定义格式然后直接用SeeClick那个basemodel微调。另外可以看一下我们最新的工作（SeeClick的升级版），[OS-Atlas](https://osatlas.github.io/)，本身具备Generalist GUI Agent的能力和未见场景的泛化性，感觉会更适合你的任务。

好的，谢谢大佬~
