### ISSUE TITLE
Inquiry about dataset used

### ISSUE THREAD

**Issue by Eman-Abdelrahman** [njucckevin/SeeClick#55]
Thanks for sharing this nice work! I wanted to ask about the dataset used for training. It seems that screen summarization dataset doesn't have bbox information. How would this data help for GUI grounding?

**Comment by Eman-Abdelrahman** [comment]
Another question, please:
for each of ricosca.json and widget_captioning.json, where can I find their corresponding images? I initially assumed the images will be in the rico_imgs.zip file, but not all images exist. 

For example in ricosca.json, there is `[{"img_filename": "32358.jpg", "instruction": "choose icon above the chapitre 1 31 app", "bbox": [0.878,.....]}],` but I couldn't find 32358.jpg in rico_imgs.zip

Thanks in advance!

**Comment by njucckevin** [comment]
Hi,

The screen summarization task is designed to maintain the general capability during the GUI grounding pre-training. For the mobile images, can you check that the image zip has been downloaded and unzipped correctly? The `32358.jpg` is exist in my case.

**Comment by Eman-Abdelrahman** [comment]
Thanks for your response, I would like to ask if you download it using the packaged zip file link.
<img width="1103" alt="image" src="https://github.com/user-attachments/assets/60bb92c1-8705-4d04-8739-64f4fb80fc32" />
