### ISSUE TITLE
数据集的格式

### ISSUE THREAD

**Issue by sugarandgugu** [njucckevin/SeeClick#56]
你好，我按照你在agent_task给出的方法，对aitw数据集处理成了SFT数据集格式。
然后我看了数据集格式的样例如下：
 {'from': 'assistant',
   'value': '{"action_type": 4, "click_point": (0.58,0.15)}'
}
我注意到assistant的value里面所有的值都会被预测。
请问作者为什么需要预测这一整个字典呢{"action_type": 4, "click_point": (0.58,0.15)}，感觉好奇怪。
还有action_type为什么直接用4呢，感觉直接用文本更符合直觉。

**Comment by sugarandgugu** [comment]
还有一个问题想请问一下，既然SFT的数据是预测一整个字典，但是我在调用model.chat方法grounding的时候，却可以直接输出坐标，例如在readme的例子中 (0.67,0.36)。这是为什么呢？求解答

**Comment by njucckevin** [comment]
字典的形式也只是一种表示动作的形式，当时只是觉得这种格式比较规整，用别的格式也是可以的；action_type的数字也只是个标记，没记错的话好像是沿用的AITW还是Auto-UI的方式，或许用文本会更直观/有利于模型学习一些。
readme中的例子是针对SeeClick(base)那个模型的，那个没有经过agent_task中的downstream agent sft训练。

**Comment by sugarandgugu** [comment]
谢谢你的回答，意思是hf上给的模型只是pretrain的没有sft，我理解的对嘛?
我刚刚看到了附录的数据集格式的response直接是坐标，感觉如果只把当前模型当做grounding agent，貌似可以不用输出那个action type。

**Comment by njucckevin** [comment]
hf上有四个[模型](https://huggingface.co/cckevinn)，分别是一个pre-train的和在三个下游任务上sft的。那个pre-train的就是我们用来测ScreenSpot，以及在下游任务sft的base model，它是直接输出坐标形式的（和GUI grounding pretraining的训练形式一样）。

**Comment by sugarandgugu** [comment]
好的谢谢！
