### ISSUE TITLE
关于response的一些小问题

### ISSUE THREAD

**Issue by LeeOrange-is-me** [njucckevin/SeeClick#58]
非常棒的一篇文章。但是我有个小问题。为什么我自己写出来的测试样例中，通过调用单个的response = model.chat(..)，得到的response仅仅是类似于"(0.12,0.23)"的元祖类型的字符串。但是，aitw_test.py 当中是 类似于"{"action_type":?, ...}"的字典类型的字符串。是因为单个调用时没有给出action_history嘛

**Comment by njucckevin** [comment]
相当于是有两个模型，SeeClick-base是主要只能做grounding任务，就是以`response = model.chat(..)`输出坐标的元组字符串；如果要用`aitw_test.py`这几个在下游任务上测试，需要用SeeClick-base在相应下游数据集上的agent数据微调一下，这些训练好的模型我们也在[hf](https://huggingface.co/cckevinn)上开源了。
另外，如果想既能做grounding又能直接做agent任务的话，欢迎试用我们的后续工作[OS-Atlas](https://osatlas.github.io/).

**Comment by LeeOrange-is-me** [comment]
好的，谢谢您的答复。
