### ISSUE TITLE
Question about data license

### ISSUE THREAD

**Issue by kig1929** [njucckevin/SeeClick#9]
Hi, Thanks for sharing interesting research:)

What are the licenses for the data used for pretraining (GUI Grounding Pre-training Data) and  evaluation (UI Grounding Benchmark: ScreenSpot)?

**Comment by njucckevin** [comment]
For the pretraining, web data is curated from the Common Crawl, so the license should follow theirs at https://commoncrawl.org/terms-of-use; mobile the is reorganized from [Widget-Captioning](https://github.com/google-research-datasets/widget-caption) and [Screen2words](https://github.com/google-research-datasets/screen2words/tree/main) from google research. The license for our annotated evaluation benchmark ScreenSpot is CC0.
